version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis